### ISSUE TITLE
Please support Autocomplete fields

### ISSUE THREAD

**Issue by bkonia** [pods-framework/pods-caldera-forms#11]
Currently, this addon doesn't support Pods Autocomplete fields. If you try to map an Autocomplete, it displays an error "No dropdown in form".

**Comment by jimtrue** [comment]
Confirmed. There is an Autocomplete field choice in Caldera Forms, but it doesn't appear to map in the Pods Processor (I get the error 'No Autocomplete field in form', though the field is created. I've even tried deleting the field and re-saving and no change.
