### ISSUE TITLE
Some user fields cannot be assigned to CF fields with Pods processor

### ISSUE THREAD

**Issue by Digitale-Substanz** [pods-framework/pods-caldera-forms#13]
Hi,

I have a Pod 'users' extending WP user type. While mapping user_meta fields created with Pods with the appropriate CF fields is self-explanatory, not all WP user fields  can be mapped because they are missing in the field selection. This is particularly the case for the fields `first_name` and `last_name`.

I want to create a front-end user profile which allows users to update their data right on the website. Just like in [Matt Cromwell's tutorial](https://www.mattcromwell.com/building-front-end-profile-editor-caldera-forms/) but with Pods to manage the user type. Editing the name of the user seems to be essential for this use case, but seems to be impossible at the moment.

Thanks,
Ronald

**Comment by jimtrue** [comment]
@Digitale-Substanz That tutorial requires the "Users Add-on"

**Comment by Digitale-Substanz** [comment]
Just for potential future users who might land on this issue: We've further discussed this issue on Pods' slack channel. As first_name and  last_name fields are not part of Pods but WP user fields, the User for Caldera plugin is necessary. This comes with another processor that connects to these particular fields. Hence, two form processors need to be set up, one for updating Pods (= user_meta data) and another one for updating default WP user fields.

**Comment by jimtrue** [comment]
Closing this one, because that is the solution. Anything User specific requires the User Profile Caldera add-on; any additional user_meta would either be passed directly with that to the User Profile or write to your Pod with the Pods Processor.
