### ISSUE TITLE
Conditionals no work when pod processor is created

### ISSUE THREAD

**Issue by gloriosky** [pods-framework/pods-caldera-forms#16]
Pods-caldera-forms is great !!!!
The conditionals created in the "conditional" boiler eyelash work well until the pod processor is created, then they do not work.
Is there any idea how to fix this?

**Comment by Ramoonus** [comment]
could you be a bit more specific, like which code are you using?

**Comment by gloriosky** [comment]
Hi Ramon, 
thanks for your reply
Wordpress 4.7.3
Caldera forms Versión 1.5.0.8
Pods 2.6.8
Pods Caldera Forms Processor  1.0.0 (this one)
And a simple plugin to taxonomies: pod-caldera-up.php (please change the extension .txt to .php)
[pod-caldera-up.txt](https://github.com/pods-framework/pods-caldera-forms/files/917484/pod-caldera-up.txt)

PROCESS
I created a form with conditionals and I tested it, all right.
when I had create a pod processor, conditionals no work.

you can see here:
(is a page with shortcodes)
http://casa.universalprotocol.es/test-form/

Thanks in advance for your interest
