### ISSUE TITLE
Mapping disappear randomly

### ISSUE THREAD

**Issue by akkolad** [pods-framework/pods-caldera-forms#17]
Sometimes, when I modify my form, which is quite big, the mapping of the treatment disappear.
It make me mad because it take me 20 minutes at least to re-edit these mapping and this is very boring and a big source of error.
I think this issue is because the save processus of the form is too long (or too short) to save this mapping.
How can I save or export this mapping to re-import it when this problem occurs ?

Thanks.

**Comment by dmsdesignz** [comment]
I had this happen today...
