### ISSUE TITLE
mapping lost

### ISSUE THREAD

**Issue by rdspradlin** [pods-framework/pods-caldera-forms#5]
When map fields to pod fields and save then exit and open the browser back up and go back to the look at the mappings they are gone and if i modify anything that requires a save i have to remap everything.

**Comment by dlincoln** [comment]
I'm seeing the same thing. Great, no AMAZING idea, but no luck (yet). ;)

**Comment by dlincoln** [comment]
to be clear: it DOES save settings when you update, and they perform as-set. It simply can't recall them when you reopen the processor (not a deal breaker, just a hassle), so changing them is impossible. 

I export my CF when it's working right, as a means of saving state wrt performance.

**Comment by pablopaul** [comment]
@Shelob9 any idea how to fix this?

**Comment by dlincoln** [comment]
My workaround: Keep the window open on the CF Form editor. As long as the window remains open, the variables remain valid. As soon as you close the window or navigate away from the form, the settings disappear. They still work, you just can't see them (easily - good luck unwrapping the .json file that exports them!).

When editing live/working forms, I clone them first, then open the CF Pods Processors I need to edit (don't touch the others, they'll survive!), and reset the parameters one by one as-needed. Then go to front end, and switch to your new/cloned form to test and eventually run it.

It's not the same as recall, but functionally close. I also take screen caps of my settings when testing complex things to make sure they work well. Finally, name your form fields and arrange them in Pods to easily correspond to your CF pick list. This will save a lot of time, and is close to a functional work around (you're just going down a list picking successive settings).

**Comment by 4ndir** [comment]
Thanks @dlincoln. That makes the plugin usable again!

**Comment by dlincoln** [comment]
YW... the workaround requires discipline but does seem stable (we've been running a Pods-linked form on CF live for a month now, no issues; we've even changed field labels and stuff. As long as I don't open the processors they stick around.

I wish we could run our whole platform on CF and Pods.

**Comment by Shelob9** [comment]
@Desertsnowman I tried to fix this. 043c0ed made it work for WP Object fields, but not the Pods fields... The array structure was wrong, no idea why this only worked for WP object fields. Can you please finish the fix?

**Comment by Desertsnowman** [comment]
I'll take a look. haven't worked in Pods for a while... this will be fun.

**Comment by paulprimaryk** [comment]
I'm still seeing similar behavior. Worse, it appears that the saved mappings break when I modify other aspects of a form, without opening the processor section. Any progress on this issue?

**Comment by jimtrue** [comment]
I'm not seeing this issue at all. I've gone back and forth multiple times with entry field to Pods processor and I'm not losing my mappings to any fields. Right now the only outstanding real issues I'm seeing are these: #7 #8 and #11 so I think the original issue was corrected.
