### ISSUE TITLE
Images do not arrive in pods

### ISSUE THREAD

**Issue by 4ndir** [pods-framework/pods-caldera-forms#7]
I set up a pods processor and all information from the form are arriving in my pods fields...except for images. They are being saved in caldera but not transfered to my pods image field. Any ideas on this? Did you try to map images?

**Comment by richstrauss** [comment]
I am having the same problem in that images are not arriving in Pods. Images are uploaded via Caldera Forms, but do not show up in neither the WordPress Media manager or the Pods entry. Any ideas greatly appreciated!

**Comment by Emohawkje** [comment]
Hey Guys, I'm having the same problem. Is there a fix for this? I know you have to use a Advance File Uploader field to get the file in the media library but I don't know how to pull the file through to pods.

**Comment by jimtrue** [comment]
@Shelob9 I can confirm (have tested) the images do write to the media library but they are not attaching to the image/file field.

**Comment by dmsdesignz** [comment]
yes I'm having the same issue

**Comment by ericmil87** [comment]
Any update?
