### ISSUE TITLE
Featured Image is Mapping

### ISSUE THREAD

**Issue by DrSammyLee** [pods-framework/pods-caldera-forms#8]
Is it possible to add a mapping to Feature Image similar to pods-gravity-forms plugin? Thanks.

**Comment by jimtrue** [comment]
Confirmed. There is an Autocomplete field choice in Caldera Forms, but it doesn't appear to map in the Pods Processor (I get the error 'No Autocomplete field in form', though the field is created. I've even tried deleting the field and re-saving and no change.
