### ISSUE TITLE
Mapping to Checkbox Error

### ISSUE THREAD

**Issue by edwin-laman7** [pods-framework/pods-caldera-forms#9]
I use PODS to create an extended user field. Then use Caldera form to input these fields. I didnt want to use the pods->form as it was really hard to control the form look and feel. So Im using Caldera to map to PODS. 

The error that I'm facing is the that caldera form couldnt save the multiple choice like, dropdown, radio button or checkbox (basically anything with more than 2 values). Basically, if we have chosen all the values, we save, then check again, the values are all missing.

On fields like normal text box works out find.

**Comment by jimtrue** [comment]
I'm not able to confirm this at all. If you have a multiple-select relationship field, using checkboxes, drop-down multiple select, the relationship choices map over.

Radio buttons only allow for single choice and they also map just fine. If you are still experiencing this issue, please submit examples and re-open.
